export const dummies = [
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "Hey! It seems that data cannot be fetched from backend API. ",
    category: "category",
  },
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "For core functionality (login, register, post) to be functional,",
    category: "category",
  },
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "please make sure that the backend API is up,",
    category: "category",
  },
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "and mongoDB database was successfully connected.",
    category: "category",
  },
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "to get more information, please refer to the guide on github page.",
    category: "category",
  },
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "In case of any problem, please feel free to react me at bogus.kania (dot) gmail.com",
    category: "category",
  },
  {
    userInfo: [{ user_id: 0, username: "dummy", avatar: "" }],
    _id: "123",
    title: "sample title",
    date: "13:39:11, 2022-05-05",
    text: "Have a great time!",
    category: "category",
  },
];
